apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: jmeter
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: jmeter-client
    name: jmeter-client
  spec:
    replicas: 3
    selector:
      app: jmeter-client
      deploymentconfig: jmeter-client
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: jmeter-client
          deploymentconfig: jmeter-client
      spec:
        containers:
        - env:
          - name: REMOTE_HOSTS
            value: jmeter-server.jmeter.svc.cluster.local
          - name: IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          image: 172.30.1.1:5000/jmeter/custom-jmeter-client@sha256:3284ac5833abfd2d5f4fec9810a5aee6b6d285eea8a94615cf62f816a15f0ad6
          imagePullPolicy: IfNotPresent
          name: jmeter-client
          ports:
          - containerPort: 1099
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /load_tests/
            name: volume-1ycv6
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: volume-1ycv6
          persistentVolumeClaim:
            claimName: test
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - jmeter-client
        from:
          kind: ImageStreamTag
          name: custom-jmeter-client:latest
          namespace: jmeter
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: jmeter-server
    name: jmeter-server
  spec:
    replicas: 1
    selector:
      app: jmeter-server
      deploymentconfig: jmeter-server
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: jmeter-server
          deploymentconfig: jmeter-server
      spec:
        containers:
        - env:
          - name: IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          image: docker.io/hhcordero/docker-jmeter-server@sha256:8b6959a8498b115d0d70a291ad2809f5397cc61e8fdfcc0a73f483410c1961a5
          imagePullPolicy: IfNotPresent
          name: jmeter-server
          ports:
          - containerPort: 1099
            protocol: TCP
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: 250m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - jmeter-server
        from:
          kind: ImageStreamTag
          name: docker-jmeter-server:latest
          namespace: jmeter
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: jmeter-client
    name: jmeter-client
  spec:
    ports:
    - name: 1099-tcp
      port: 1099
      protocol: TCP
      targetPort: 1099
    selector:
      app: jmeter-client
      deploymentconfig: jmeter-client
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: jmeter-server
    name: jmeter-server
  spec:
    ports:
    - name: 1099-tcp
      port: 1099
      protocol: TCP
      targetPort: 1099
    selector:
      app: jmeter-server
      deploymentconfig: jmeter-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: custom-jmeter-client
    name: custom-jmeter-client
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: custom-jmeter-client:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/hhcordero/docker-jmeter-client
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: docker-jmeter-server:latest
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: 1LnGb_wsIce14uR-ILfE
      type: GitHub
    - generic:
        secret: 2StG6U-nilbjyPLMQV8k
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":0,"currentAverageValue":"1m"}}]'
    creationTimestamp: null
    labels:
      app: jmeter-server
    name: jmeter-server
  spec:
    maxReplicas: 4
    minReplicas: 1
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: DeploymentConfig
      name: jmeter-server
    targetCPUUtilizationPercentage: 80
  status:
    currentCPUUtilizationPercentage: 0
    currentReplicas: 1
    desiredReplicas: 1
    lastScaleTime: 2017-12-23T11:26:35Z
